# Generated by Django 4.1 on 2023-10-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_user_room_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='MaxPlayers',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='MinPlayers',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='PuzzlePathDesign',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='Scenario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
