# Generated by Django 4.1 on 2023-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_maxplayers_room_minplayers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='MaxPlayers',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='MinPlayers',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='PuzzlePathDesign',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='Scenario',
            field=models.TextField(default='A scenario'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Title',
            field=models.CharField(default='A room', max_length=50),
        ),
    ]
