# Generated by Django 4.1 on 2023-10-13 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rooms', '0005_puzzle_room_brief_room_debrief_room_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='MaxPlayers',
            new_name='maxPlayers',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='MinPlayers',
            new_name='minPlayers',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='PuzzlePathDesign',
            new_name='puzzlePathDesign',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Scenario',
            new_name='scenario',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='room',
            name='User_ID',
        ),
        migrations.AddField(
            model_name='room',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
