# Generated by Django 4.1 on 2023-10-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0013_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='timeLimit',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='A room', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
