# Generated by Django 4.1 on 2023-10-28 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_alter_room_timelimit_alter_room_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='timeLimit',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
