# Generated by Django 4.1 on 2023-11-06 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_alter_room_timelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='brief',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='debrief',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='goal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='maxPlayers',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='minPlayers',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='puzzlePathDesign',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='scenario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='timeLimit',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
