# Generated by Django 4.1 on 2023-11-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_alter_room_brief_alter_room_debrief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='puzzlePathDesign',
            field=models.CharField(blank=True, choices=[('linear', 'Linear'), ('multiLinear', 'Multi-Linear'), ('open', 'Open')], max_length=50),
        ),
    ]
