# Generated by Django 4.1 on 2023-11-09 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_alter_room_difficulty_alter_room_puzzlepathdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='debrief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hasActor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='maxPlayers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='minPlayers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='puzzlePathDesign',
            field=models.CharField(blank=True, choices=[('linear', 'Linear'), ('multiLinear', 'Multi-Linear'), ('open', 'Open')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='timeLimit',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
