# Generated by Django 4.1 on 2023-11-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_alter_room_brief_alter_room_debrief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subroom',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
