# Generated by Django 4.1 on 2023-11-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_alter_subroom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subroom',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', to_field='title'),
        ),
    ]
