# Generated by Django 4.1 on 2023-11-09 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0022_alter_subroom_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subroom',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subRooms', to='rooms.room'),
        ),
    ]
