# Generated by Django 4.1 on 2023-11-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0023_alter_subroom_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='subRoomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='rooms.subroom'),
        ),
    ]
