# Generated by Django 4.1 on 2023-11-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0026_puzzle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='description',
            field=models.TextField(default='A description', null=True),
        ),
    ]
