# Generated by Django 4.1 on 2023-11-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0028_alter_solution_puzzleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='puzzleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='rooms.puzzle'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='puzzleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='rooms.puzzle'),
        ),
    ]
