# Generated by Django 4.1 on 2023-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_alter_hint_puzzleid_alter_reward_puzzleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='condition',
            field=models.TextField(default='A condition'),
        ),
    ]
